config/routes.rb
Rails.application.routes.draw do
  get 'forms/new'
  get 'forms/destroy'
  root 'top#index'
  get 'sign_in', to: 'user/sessions#new'
  delete 'sign_out', to: 'user/sessions#destroy'
  get 'sign_up', to: 'user/registrations#new'

  resources :top, only: %i[show]

  namespace :user do
    resources :registrations, only: :create
    resources :sessions, only: :create
    resource :mypages, only: %i[show edit update]
  end

  resources :books

  resources :forms, only: %i[new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :bigint           not null, primary key
#  image      :string
#  publisher  :string
#  status     :integer          default(0), not null
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_books_on_user_id  (user_id)
#

class Book < ApplicationRecord
    mount_uploader :image, ImagesUploader

    has_one :subject, dependent: :destroy
    has_one :form, dependent: :destroy
    belongs_to :user
end

app/models/form.rb
# == Schema Information
#
# Table name: forms
#
#  id         :bigint           not null, primary key
#  day        :date
#  form_uid   :bigint
#  place      :string
#  status     :integer
#  time       :time
#  to_uid     :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :bigint           not null
#
# Indexes
#
#  index_forms_on_book_id  (book_id)
#
# Foreign Keys
#
#  fk_rails_...  (book_id => books.id)
#  fk_rails_...  (form_uid => users.id)
#  fk_rails_...  (to_uid => users.id)
#

class Form < ApplicationRecord
  belongs_to :book
  belongs_to :from_user, class_name: "User", foreign_key: 'form_uid'
  belongs_to :to_user, class_name: "User", foreign_key: 'to_uid'
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :bigint           not null, primary key
#  grade      :integer
#  name       :string
#  semester   :integer
#  teacher    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :bigint
#
# Indexes
#
#  index_subjects_on_book_id  (book_id)
#

class Subject < ApplicationRecord
    belongs_to :book
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :bigint           not null, primary key
#  crypted_password   :string
#  current_login_at   :datetime
#  current_login_ip   :string
#  email              :string
#  failed_login_count :integer          default(0), not null
#  introduction       :string
#  last_login_at      :datetime
#  last_login_ip      :string
#  last_request_at    :datetime
#  login_count        :integer          default(0), not null
#  name               :string
#  password_salt      :string
#  persistence_token  :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class User < ApplicationRecord
    acts_as_authentic
    has_many :books, dependent: :destroy
    has_many :app_form, class_name: 'Form', foreign_key: 'form_uid', dependent: :destroy
    has_many :app_to, class_name: 'Form', foreign_key: 'to_uid', dependent: :destroy
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    # ログイン必須controllerのbefore_actionで呼ぶ
    def require_login
      return redirect_to sign_in_path unless current_user
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_books, only: %i[show destroy]

  def index
    @books = User.find(current_user.id).books
  end

  def new
    @book = Book.new
  end

  def create
    user = current_user
    @book = user.books.build(book_params)

    if @book.save
      redirect_to books_url
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def destroy
    @book.destroy
    redirect_to books_url
  end

  private
    def set_books
      @book = current_user.books.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :publisher, :image)
    end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def new
    @book_id = params[:book_id]
    @book_user = Book.find(@book_id).user.id
    @customer = current_user.id
  end

  def destroy
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/user/mypages_controller.rb
class User::MypagesController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end

  def edit
  end

  def update
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_mypages_url
    else
      render action: :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)
    if @user_session.save
      redirect_to user_mypages_url
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user/registrations_helper.rb
module User::RegistrationsHelper
end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/views/books/edit.html.slim
h1 Books#edit
p Find me in app/views/books/edit.html.slim

app/views/books/index.html.erb
 <% @books&.each do |book| %>
 <div class="card">
    <%= image_tag book.image.to_s, size: '300x300', class:"card-img-top"%>
  <div class="card-body">
    <h4 class="card-title"><%=book.title%></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%=book.publisher%></h6>
    <p class="card-text">
      タグ、タグ、タグ、タグ
    </p>
   <%= link_to '詳細', book_path(book.id), class: "btn btn-success" %>
   <%= link_to '編集', book_path(book.id), class: "btn btn-secondary" %>
   <%= link_to '削除', book_path(book.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %>
  </div>
 </div>
 <% end %>

app/views/books/new.html.erb
<h1> 本投投稿ページ </h1>

<%= form_with model: @book, url: books_url, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "〇〇の本"%>
  </div>
  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.text_field :publisher, class: "form-control", placeholder: "〇〇社"%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <%= f.submit "投稿" %>
<% end %>

app/views/books/show.html.erb
<h1>本詳細&取引動線</h1>
<div class="card"　style="width: 70%;">
<%= image_tag @book.image.to_s, size: '300x300', class:"card-img-top"%>
<div class="card-body">
    <h4 class="card-title"><%=@book.title%></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%=@book.publisher%></h6>
    <p class="card-text">タグ、タグ、タグ、タグ</p>
    <p class="card-text">取引ボタンをクリックすると、注文表が発行される</p>
    <%= link_to '戻る', root_path, class: "btn btn-secondary" %>
    <%= link_to '取引表を記入', new_form_path, class: "btn btn-success" %>
</div>
</div>

app/views/forms/new.html.erb
<form>
  <fieldset disabled>
    <div class="form-group">
      <label for="formGroupExampleInput">この本の所有者_ID</label>
      <input type="text" class="form-control" id="formGroupExampleInput" placeholder=<%= @book_user %>>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">この本のクライアント_ID</label>
      <input type="text" class="form-control" id="formGroupExampleInput2" placeholder=<%= @customer %>>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">本ID</label>
      <input type="text" class="form-control" id="formGroupExampleInput2" placeholder=<%= @book_id %>>
    </div>
  </fieldset>
  <div class="form-group">
    <label for="formGroupExampleInput2">場所</label>
    <select class="custom-select">
        <option selected>受け渡し場所の選択</option>
        <option value="1">食堂</option>
        <option value="2">図書館</option>
        <option value="3">生協</option>
    </select>
  </div>
  <div class="form-group event__start-time">
    <label for="start_time">日付</label>
    <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
        <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">時間</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
  </div>

</form>

<%# <%= javascript_pack_tag 'form/new' %> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collemeri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%# レスポンシブ対応 コードの意味はわからない%>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <%= link_to_unless_current "カレメリ", '/', class: "nav-link"%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to "ログアウト",sign_out_path, class: "nav-link", method: :delete%>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ",user_mypages_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">取引管理</a>
                </li>
                <li class="nav-item">
                  <%= link_to "投稿",new_book_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to "投稿一覧",books_path, class: "nav-link"%>
                </li>
              <% else %>
                <li class="nav-item active">
                  <%= link_to "ログイン",sign_in_path, class: "nav-link" %>
                </li>
                <li class="nav-item active">
                  <%= link_to "新規登録",sign_up_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>

      <div class="container" id="wrapper">
          <%= yield %>
      </div>

      <footer>
        <nav class="navbar navbar-dark bg-primary">
          <a class="navbar-brand" href="#!">Fixed bottom</a>
        </nav>
      </footer>
  </body>
</html>

app/views/top/index.html.erb
<div class="row">
    <% @books&.each do |book| %>
    <div class="col-md-2 col-lg-4">
        <div class="card">
        <%= image_tag book.image.to_s, size: '300x300', class:"card-img-top"%>
        <div class="card-body">
            <h4 class="card-title"><%=book.title%></h4>
            <h6 class="card-subtitle mb-2 text-muted"><%=book.publisher%></h6>
            <p class="card-text">タグ、タグ、タグ、タグ</p>
            <%= link_to '取引詳細', top_path(book.id), class: "btn btn-success" %>
        </div>
        </div>
    </div>
    <% end %>
</div>

app/views/top/show.html.erb
<h1>本詳細&取引動線</h1>
<div class="card"　style="width: 70%;">
<%= image_tag @book.image.to_s, size: '300x300', class:"card-img-top"%>
<div class="card-body">
    <h4 class="card-title"><%=@book.title%></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%=@book.publisher%></h6>
    <p class="card-text">タグ、タグ、タグ、タグ</p>
    <p class="card-text">取引ボタンをクリックすると、注文表が発行される</p>
    <%= link_to '戻る', root_path, class: "btn btn-secondary" %>
    <%= link_to '取引表を記入', new_form_path(book_id: @book.id), class: "btn btn-success" %>
</div>
</div>

app/views/user/mypages/edit.html.slim
h1 User::User#edit
p Find me in app/views/user/user/edit.html.slim

app/views/user/mypages/show.html.slim
h1 プロフィール

h2 名前:#{@user&.name}
h2 メールアドレス:#{@user&.email}
h2 自己紹介分：#{@user&.introduction}

app/views/user/mypages/update.html.slim
h1 User::User#update
p Find me in app/views/user/user/update.html.slim